title: "Xander Bystrom"
description: "bystromxander@gmail.com | <a style=\"color:white;text-decoration: underline;\", href=\"https://www.linkedin.com/in/xander-bystrom\">LinkedIn</a>"
show_downloads: false 

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme